# Generated by Django 5.2.7 on 2025-11-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True)),
            ],
        ),
    ]
